import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";

import { Button } from "@heroui/react";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.variable} font-sans`}>
        <div className="py-4 flex items-center justify-between w-[80%] mx-auto">
          <Button variant="ghost" className="text-xl font-bold">
            StudyFlow
          </Button>
          <div>
            <Button variant="ghost" className="text-md font-semibold">
              Dashboard
            </Button>
            <Button variant="ghost" className="text-md font-semibold">
              Reflections
            </Button>
          </div>
          <Button variant="danger-soft" className="text-md font-semibold">
            Logout
          </Button>
        </div>
        {children}
      </body>
    </html>
  );
}
